### ISSUE TITLE
Roll all dice issue when dice are selected

### ISSUE THREAD

**Issue by morana21** [mooreka21/CosmicWimpoutGameState#1]
Step to recreate:
1. run the game
2. click roll dice
3. end turn
4. check select this dice box for 1-4 dice
5. roll all dice

N. game does not allow you to roll all dice if one is selected, roll all dice should disregard how many are selected

**Comment by mooreka21** [comment]
We tried to recreate this issue and the pop up text view says it’s an illegal move to select the dice before hitting “roll all dice”. This must be what happened for you because it still allows the player to roll all 5 dice when hitting “roll all dice” even with the boxes checked.

**Comment by morana21** [comment]
sounds good, did not see the illegal move popup
