### ISSUE TITLE
Red screen bug

### ISSUE THREAD

**Issue by gerylkvinoya** [mooreka21/CosmicWimpoutGameState#10]
Steps to recreate:
Launch local game
Go through a turn
While the computers are going through their turns, press “Roll Dice” and “End Game” at the same time

**Comment by mooreka21** [comment]
Thank you for finding this bug! We will work on fixing it.

**Comment by mooreka21** [comment]
This bug has been fixed.

**Comment by gerylkvinoya** [comment]
Can confirm that the bug has been fixed
