### ISSUE TITLE
How to play button doesn't work. 

### ISSUE THREAD

**Issue by b1n2bash** [mooreka21/CosmicWimpoutGameState#11]
Does not display the rules when you click : "how to play" - pirkl21

**Comment by mooreka21** [comment]
Yeah, it isn't supposed to work yet. We are planning to implement this for the final release so that when clicked, a new screen will pop up displaying the rules of the game.

**Comment by mooreka21** [comment]
We now have this feature implemented and it is working smoothly.

**Comment by b1n2bash** [comment]
Very cool! Thanks, Sam!
