### ISSUE TITLE
Turn Automatically Ends

### ISSUE THREAD

**Issue by SydneyWells** [mooreka21/CosmicWimpoutGameState#15]
If you reroll your dice 3 times, the game automatically ends your turn with 0 pts, even if you should be gaining points. 
This is an issue because it means you don't really get to play.

**Comment by slemly** [comment]
This was examined and we didn't find anything - we think you might be wimping out.

**Comment by SydneyWells** [comment]
I verified that the issue was apparently just due to me (and perhaps your teammate?) being confused about the rules of the game.
