### ISSUE TITLE
Scoring Issue

### ISSUE THREAD

**Issue by AverageGatsby98** [mooreka21/CosmicWimpoutGameState#3]
Steps to repeat:
1)Get dice to be "5, stars, 5, bolt square, bolt squre"
2) The score should be 10 points but it says I get 20
other case
1) Get dice to be "tri-force, tri-force, sun, bolt square, tri-force"
2) Score should be either 35 or 40 (based on wild die), but it says it's 60 points

**Comment by dendinge21** [comment]
The second bug in this comment, is duplicated. See other issue in this repo. 
First bug mentioned, debug score calculation method to see where the issue went wrong .

**Comment by AverageGatsby98** [comment]
They fixed the counting error
