### ISSUE TITLE
Possible scoring bug

### ISSUE THREAD

**Issue by robinsph21** [mooreka21/CosmicWimpoutGameState#4]
Steps to recreate:

Run game
Get a set of 3 through a wild-card
The game counts the run of three plus the 10 from the wild sun in scoring possibly. 

I'm 90% sure, so there is some uncertainty, but I'm fairly sure I was scored incorrectly with the wild card.
I got an extra 10 points when I shouldn't have.

**Comment by dendinge21** [comment]
A legitimate bug, I think i know what is happening. In the method that calculates the score, its tallying up the score at the flash section and the flaming sun section. We can fix this by adding an if else statement or something along those lines

**Comment by robinsph21** [comment]
Scoring looks like it has been updated properly, I noticed no other problems.
