### ISSUE TITLE
Unable to Wimpout

### ISSUE THREAD

**Issue by nelsons19** [mooreka21/CosmicWimpoutGameState#5]
Steps to recreate:
1) start game and roll all your dice
2) select only the center black die
3) continually press the roll selected die button
4) the score goes up but the player never wimps out
This allows the player to win during their first turn every time

**Comment by campbeld21** [comment]
This was a result of an older version of the code. The problem has been fixed.

**Comment by nelsons19** [comment]
I can wimp out now good job!
