### ISSUE TITLE
Cannot roll dice!

### ISSUE THREAD

**Issue by malikh22** [mooreka21/CosmicWimpoutGameState#6]
1. Started a game
2. Attempted to roll 4 dice
3. Nothing happened. No errors, nothing in the GUI changed. 
4. Attempted to roll 3 dice 
5. Nothing happened. No errors, nothing in the GUI changed.
6. Attempted to roll a single die
7. Nothing happened. No errors, nothing in the GUI changed. I don’t think it’s possible to play if you can’t roll, which is bad. If I was making illegal moves, there should be some kind of notification.

**Comment by dendinge21** [comment]
Illegitimate, by design. Must roll all 5 dice to begin. We should add a message that pops up that explains this.

**Comment by malikh22** [comment]
It could also be helpful to rename the buttons. Someone could attempt to roll all five dice using the "Roll selected die" button while all dice were selected, and it would not work. The labels for your buttons in the GUI are a little confusing. None of them explicitly said "Roll all dice".

**Comment by malikh22** [comment]
The game is now easier to navigate.
