### ISSUE TITLE
"Must Reroll Dice 1 and 2"

### ISSUE THREAD

**Issue by slemly** [mooreka21/CosmicWimpoutGameState#7]
After getting a flash with the following setup:
dice 1 = triangles
dice 2 = 5
dice 3, 4, 5 = lightning bolts

I am unable to roll dice 1 and 2 despite the game telling me I must roll those to clear the flash. 
I can select them and hit roll selected dice, but am unable to roll them as the game doesn't respond at that point.

**Comment by mooreka21** [comment]
I had that same issue too in some cases. I told Olivia about it & she said she knows how to fix it
